---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to deploy an EC2 instance with an Elastic IP, attached volume, and

Parameters:
  Environment:
    Description: Deployment environment (e.g., Dev, Staging, Prod)
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Staging
      - Prod
    ConstraintDescription: "Must be a valid environment type (Dev, Staging, Prod)."

  OS:
    Description: Operating system for the EC2 instance (Amazon Linux, Ubuntu)
    Type: String
    Default: AmazonLinux
    AllowedValues:
      - AmazonLinux
      - Ubuntu
    ConstraintDescription: "Must be AmazonLinux or Ubuntu."

  Region:
    Description: AWS region for the EC2 instance and resources
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - ap-south-1
    ConstraintDescription: "Must be a valid AWS region. Must be N.Virginia or Mumbai"

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: "Must be a valid EC2 instance type."

    VolumeSize:
      Description: Size of the EBS volume in GiB
      Type: Number
      Default: 10
      MinValue: 1
      MaxValue: 16384
      ConstraintDescription: "Must be a valid volume size between 1 and 16384 GiB."

    Mappings:
      EnvironmentAMI:
        us-east-1:
          Prod:
            AmazonLinux: ami-063d43db0594b521b
            Ubuntu: ami-063d43db0594b521b
          Dev:
            AmazonLinux: ami-063d43db0594b521b
            Ubuntu: ami-063d43db0594b521b
          Staging:
            AmazonLinux: ami-063d43db0594b521b
            Ubuntu: ami-063d43db0594b521b
        ap-south-1:
          Prod:
            AmazonLinux: ami-063d43db0594b521b
            Ubuntu: ami-063d43db0594b521b
          Dev:
            AmazonLinux: ami-063d43db0594b521b
            Ubuntu: ami-063d43db0594b521b
          Staging:
            AmazonLinux: ami-063d43db0594b521b
            Ubuntu: ami-063d43db0594b521b

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap  [EnvironmentAMI, !Ref Region, !Ref Environment, !Ref OS]
      AvailabilityZone: !Select [ 0, !GetAZs !Ref Region ]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-EC2Instance"

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

  EC2Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref VolumeSize
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Encrypted: true
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-EC2Volume"

  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref EC2Volume
      Device: /dev/sdf
      
Outputs:
  InstanceId:
    Description: ID of the newly created EC2 instance
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !Ref ElasticIP

  VolumeId:
    Description: ID of the attached EBS volume
    Value: !Ref EC2Volume

  Environment:
    Description: The deployment environment of the EC2 instance
    Value: !Ref Environment

  OperatingSystem:
    Description: The operating system selected for the EC2 instance
    Value: !Ref OS

  InstanceRegion:
    Description: The AWS region where the EC2 instance is deployed
    Value: !Ref Region
